### ISSUE TITLE
new QR scanning lib is sloooow

### ISSUE THREAD

**Issue by isysd** [CTMGuild/ctm-machine#15]
In the latest alpha branch, the proprietary QR scanning lib 'manatee' was replaced by open source lib 'jsqrcode'. After some testing, however, it seems that jsqrcode is not as good at finding the "finder patterns" that identify a QR code. Either the use of this library needs to be improved so that it can perform better, or another open source alternative needs to be identified.

This is by far the highest priority open issue.

**Comment by hues0** [comment]
current jsqrcode does very fine with my webcam, some improvements could be made but this is currently functional

**Comment by isysd** [comment]
This did seem to be a hardware specific issue. The jpeg frames coming from the camera were missing a Huffman table. This is now an alternative, on the 'png' branch.

https://github.com/CTMGuild/ctm-machine/commit/0a037e4be140b77369058d6282221051b44ac7cf
